repos:
  - repo: local
    hooks:
      - id: make-pre-commit
        name: Run Makefile checks
        entry: uv run make pre-commit
        language: system            # use system Python / shell
        pass_filenames: false       # Make handles its own paths